export { createCommand, type CommandDefinition, type CommandHandlerContext, type CommandInput, type CommandResult } from "./commands/create-command";
export { createMenuItem, createMenuRoot, createShortcut, createToolbarItem, type MenuCommandContribution, type MenuContribution, type MenuContributionBase, type MenuRootContribution, type MenuSubmenuContribution, type MenuToggleContribution, type ShortcutContribution, type ToolbarContribution } from "./contributions/descriptors";
export { isContributionEnabled, isContributionVisible, type ContributionStatePredicate, type WhenPredicate } from "./contributions/when";
export { createExtensionPoint, type ContributionReader, type ExtensionContribution, type ExtensionPoint, type ExtensionPointOptions, type ResolvedContribution } from "./extensions/extension-point";
export { createEventEmitter, type EventEmitter, type EventMap } from "./events/typed-event-emitter";
export { disposable, createDisposableScope, type Disposable, type DisposableScope } from "./lifecycle/disposable";
export { createMessage, createTranslationBundle, type MessageDefinition, type MessageReader, type MessageService, type TranslationBundle } from "./messages/message-service";
export { PlatformError, platformErrorCodes, isPlatformError, type PlatformErrorCode, type PlatformErrorOptions } from "./errors/platform-error";
export { createApplication, createPlatform, type ApplicationFactoryOptions, type CommandExecutor, type DiagnosticsService, type Platform, type PlatformDiagnosticSnapshot, type PlatformFactoryOptions, type PlatformUiReader, type PluginController, type PluginEvent, type PluginSnapshot, type PluginState, type ServiceReader } from "./plugins/platform";
export { createPlugin, createPluginToken, type DependencyRequirement, type PluginDefinition, type PluginSetup, type PluginSetupContext, type PluginToken } from "./plugins/plugin-api";
export { provideService, type ServiceFactoryContext, type ServiceProvider } from "./services/provider";
export { createServiceToken, type ServiceToken } from "./services/tokens";
export { createSetting, type SettingControl, type SettingDefinition, type SettingsReader, type SettingsService, type SettingsStorage, type SettingScope, type SettingValue } from "./settings/settings-registry";
export { defineMessage, type LocalizedText, type MessageDescriptor, type MessageParams } from "./text/messages";
export { SchemaValidationError, validateSchema, type InferSchemaOutput, type StandardSchemaIssue, type StandardSchemaLike, type StandardSchemaResult } from "./validation/schema";
